# Generated by Django 2.1.1 on 2018-10-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_post_importantlinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmitCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('post_by', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('img_link', models.CharField(max_length=200)),
            ],
        ),
    ]
