# Generated by Django 2.1.1 on 2018-10-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_admitcards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admitcards',
            name='link',
        ),
        migrations.AddField(
            model_name='admitcards',
            name='apply_link',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='admitcards',
            name='img_link',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
