# Generated by Django 2.1.1 on 2018-10-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importantdates',
            name='last_date',
        ),
        migrations.AddField(
            model_name='importantdates',
            name='content',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
