# Generated by Django 2.1.1 on 2018-10-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20181002_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importantlinks',
            name='apply',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='importantlinks',
            name='extra_info',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='importantlinks',
            name='notification',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='importantlinks',
            name='o_website',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='importantlinks',
            name='syllabus',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
