# Generated by Django 2.1.1 on 2018-10-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20181002_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='last_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
