# Generated by Django 2.1.1 on 2018-10-03 18:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20181003_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='last_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
