# Generated by Django 2.1.1 on 2018-10-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20181005_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='importantlinks',
        ),
        migrations.AddField(
            model_name='post',
            name='apply',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='extra_info',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='notification',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='o_website',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='syllabus',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='ImportantLinks',
        ),
    ]
