# Generated by Django 2.1.2 on 2018-10-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20181009_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='qualification',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='state',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
