# Generated by Django 2.1.2 on 2019-01-13 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default=None, max_length=400, null=True)),
                ('a1', models.CharField(default=None, max_length=400, null=True)),
                ('a2', models.CharField(default=None, max_length=400, null=True)),
                ('a3', models.CharField(default=None, max_length=400, null=True)),
                ('a4', models.CharField(default=None, max_length=400, null=True)),
                ('a5', models.CharField(default=None, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_questions', models.IntegerField(blank=True, default=0, null=True)),
                ('time', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Test'),
        ),
    ]
