# Generated by Django 2.1.2 on 2019-01-13 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20190113_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='time',
            new_name='time_for_test',
        ),
    ]
