# Generated by Django 2.1.2 on 2019-01-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20190113_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_title',
            field=models.CharField(default=None, max_length=400, null=True),
        ),
    ]
