# Generated by Django 2.1.2 on 2019-01-13 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_test_test_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AptitudeTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(default=None, max_length=400, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='all_test',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.AptitudeTest'),
        ),
    ]
