# Generated by Django 2.1.2 on 2019-01-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_aptitudetest_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_num',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
