# Generated by Django 2.1.2 on 2019-01-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_question_question_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_category',
            field=models.CharField(default=None, max_length=400, null=True),
        ),
    ]
