# Generated by Django 2.1.2 on 2019-01-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_test_test_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='job_like_status',
            field=models.BooleanField(default=False),
        ),
    ]
