# Generated by Django 2.1.2 on 2019-01-31 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_userblog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='job_like_status',
        ),
    ]
