# Generated by Django 2.1.2 on 2019-01-31 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_test_test_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(default=None, max_length=400, null=True)),
                ('category_description', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default=None, max_length=400, null=True)),
                ('question_num', models.IntegerField(blank=True, default=0, null=True)),
                ('a1', models.CharField(default=None, max_length=400, null=True)),
                ('a2', models.CharField(default=None, max_length=400, null=True)),
                ('a3', models.CharField(default=None, max_length=400, null=True)),
                ('a4', models.CharField(default=None, max_length=400, null=True)),
                ('a5', models.CharField(default=None, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ETest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_title', models.CharField(default=None, max_length=400, null=True)),
                ('test_category', models.CharField(default=None, max_length=400, null=True)),
                ('test_description', models.TextField(default=None, null=True)),
                ('num_of_questions', models.IntegerField(blank=True, default=0, null=True)),
                ('time_for_test', models.IntegerField(blank=True, default=0, null=True)),
                ('all_test', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.EnglishTest')),
            ],
        ),
        migrations.CreateModel(
            name='ReasoningTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(default=None, max_length=400, null=True)),
                ('category_description', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default=None, max_length=400, null=True)),
                ('question_num', models.IntegerField(blank=True, default=0, null=True)),
                ('question_img_link', models.CharField(default=None, max_length=200, null=True)),
                ('a1', models.CharField(default=None, max_length=400, null=True)),
                ('a2', models.CharField(default=None, max_length=400, null=True)),
                ('a3', models.CharField(default=None, max_length=400, null=True)),
                ('a4', models.CharField(default=None, max_length=400, null=True)),
                ('a5', models.CharField(default=None, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_title', models.CharField(default=None, max_length=400, null=True)),
                ('test_category', models.CharField(default=None, max_length=400, null=True)),
                ('test_description', models.TextField(default=None, null=True)),
                ('num_of_questions', models.IntegerField(blank=True, default=0, null=True)),
                ('time_for_test', models.IntegerField(blank=True, default=0, null=True)),
                ('all_test', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ReasoningTest')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='question_img_link',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rquestion',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RTest'),
        ),
        migrations.AddField(
            model_name='equestion',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ETest'),
        ),
    ]
